/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK */

#ifndef _Included_com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK
#define _Included_com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK
 * Method:    TTSStartRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK_tTSStartRequest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK
 * Method:    TTSGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK_tTSGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK
 * Method:    TTSSetGlobalConfig
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_baidu_speech_jserverttssdk_JBDSpeechTTSSDK_tTSSetGlobalConfig
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
